import { createApp } from "vue";
import "@fontsource/roboto/latin-400.css";
import "@fontsource/roboto/latin-500.css";
import "@fontsource/roboto/latin-700.css";
import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  faSquare as faSquareRegular,
  faNoteSticky as faNoteStickyRegular,
  faAlarmClock as faAlarmClockRegular,
} from "@fortawesome/free-regular-svg-icons";
import {
  faArrowPointer,
  faFont,
  faUndo,
  faRedo,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faRotateLeft,
  faFillDrip,
  faBorderAll,
  faLock,
  faLockOpen,
  faLayerGroup,
  faAnglesUp,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowsLeftRight,
  faAnglesDown,
  faClone,
  faCopy,
  faPaste,
  faTrash,
  faTableCellsLarge,
  faMagnet,
  faObjectGroup,
  faMinus,
  faPlus,
  faEllipsis,
  faGripLines,
  faAlignLeft,
  faAlignCenter,
  faAlignRight,
  faBold,
  faItalic,
  faUnderline,
  faArrowUpAZ,
  faTextHeight,
  faXmark,
  faImage,
  faRightFromBracket,
  faUpload,
  faDownload,
  faFileCode,
  faFileImage,
  faBars,
  faThumbsUp,
  faCheck,
  faStop,
  faUser,
  faFilter,
  faEllipsisVertical,
  faBoxArchive,
  faPenToSquare,
} from "@fortawesome/free-solid-svg-icons";
import App from "./App.vue";
import router from "./router";

library.add(
  faArrowPointer,
  faFont,
  faSquareRegular,
  faNoteStickyRegular,
  faAlarmClockRegular,
  faUndo,
  faRedo,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faRotateLeft,
  faFillDrip,
  faBorderAll,
  faLock,
  faLockOpen,
  faLayerGroup,
  faAnglesUp,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowsLeftRight,
  faAnglesDown,
  faClone,
  faCopy,
  faPaste,
  faTrash,
  faTableCellsLarge,
  faMagnet,
  faObjectGroup,
  faMinus,
  faPlus,
  faEllipsis,
  faGripLines,
  faAlignLeft,
  faAlignCenter,
  faAlignRight,
  faBold,
  faItalic,
  faUnderline,
  faArrowUpAZ,
  faTextHeight,
  faXmark,
  faImage,
  faRightFromBracket,
  faUpload,
  faDownload,
  faFileCode,
  faFileImage,
  faBars,
  faThumbsUp,
  faCheck,
  faStop,
  faUser,
  faFilter,
  faEllipsisVertical,
  faBoxArchive,
  faPenToSquare,
);

createApp(App).use(router).component("font-awesome-icon", FontAwesomeIcon).mount("#app");
